// =================================================================================================
//  ADMIN: CLEAR USER BLOCKLIST (!clearblocklist) - v12.2 - Fixed Mentions
// =================================================================================================
//  - [FIX] Ensures clean @[user] start for both Twitch and YouTube.
//  - [FIX] Prevents double mentions if template already includes the username.
// =================================================================================================
using System;
using System.IO;
using System.Collections.Generic;
using TranslationBot;

public class CPHInline
{
    // --- CLASS LEVEL VARIABLES (Required for helpers to see them) ---
    private BotConfig config;
    private Dictionary<string, Dictionary<string, string>> messageTemplates;
    // Set to TRUE to clear USERS. Set to FALSE to clear WORDS (for !clearwordlist command)
    private const bool CLEAR_USERS = true;
    public bool Execute()
    {
        string platform = args.ContainsKey("commandSource") && args["commandSource"].ToString().ToLower() == "youtube" ? "youtube" : "twitch";
        string moderator = args["user"].ToString();
        string moderatorId = args["userId"].ToString();
        Action<string, string> logger = (s, m) =>
        {
        };
        // Load data into class variables
        config = BotHelpers.LoadJsonFile<BotConfig>(BotConstants.CONFIG_FILENAME, logger);
        messageTemplates = BotHelpers.LoadJsonFile<Dictionary<string, Dictionary<string, string>>>(BotConstants.TEMPLATES_FILENAME, logger);
        if (config == null || messageTemplates == null)
        {
            // Simple fallback if config fails
            string errorMsg = $"@{moderator}, Critical error: Config missing.";
            if (platform == "youtube")
                CPH.SendYouTubeMessage(errorMsg);
            else
                CPH.SendMessage(errorMsg);
            return false;
        }

        // Proactive Logging
        UserProfile modProfile = BotHelpers.GetOrUpdateProfile(moderatorId, moderator, config, logger);
        string responseKey;
        bool isEmpty;
        if (CLEAR_USERS)
        {
            isEmpty = config.UserBlocklist.Count == 0;
            if (!isEmpty)
            {
                config.UserBlocklist.Clear();
                BotHelpers.SaveConfigFile(config, logger);
            }

            responseKey = isEmpty ? "adminClearBlocklistEmpty" : "adminClearBlocklistConfirm";
        }
        else
        {
            isEmpty = config.WordBlocklist.Count == 0;
            if (!isEmpty)
            {
                config.WordBlocklist.Clear();
                BotHelpers.SaveConfigFile(config, logger);
            }

            responseKey = isEmpty ? "blockListWordsEmpty" : "adminClearBlocklistConfirm";
        }

        SendMessageWithStyle(responseKey, modProfile, platform, moderator);
        return true;
    }

    // --- HELPERS ---
    private string GetBotMessage(UserProfile profile, string baseKey, Dictionary<string, object> args = null)
    {
        if (args == null || args.Count == 0)
            return BotHelpers.GetBotMessage(profile, baseKey, messageTemplates, new object[0]);
        int maxIndex = -1;
        foreach (var key in args.Keys)
        {
            if (int.TryParse(key, out int index))
            {
                if (index > maxIndex)
                    maxIndex = index;
            }
        }

        if (maxIndex == -1)
            return BotHelpers.GetBotMessage(profile, baseKey, messageTemplates, new object[0]);
        object[] positionalArgs = new object[maxIndex + 1];
        for (int i = 0; i <= maxIndex; i++)
        {
            string key = i.ToString();
            positionalArgs[i] = args.ContainsKey(key) ? args[key] : "";
        }

        return BotHelpers.GetBotMessage(profile, baseKey, messageTemplates, positionalArgs);
    }

    // =========================================================================================
    // FIX APPLIED HERE: Consistent Messaging Wrapper
    // =========================================================================================
    private void SendAdminMessage(string message, string platform, string moderator)
    {
        // 1. If the message generated by the template already starts with the username, strip it out.
        if (message.StartsWith(moderator))
        {
            message = message.Substring(moderator.Length);
        }

        // 2. Clean up any leftover punctuation/spacing at the start
        message = message.TrimStart(',', ' ', ':');
        // 3. Force the @mention at the start
        string finalMessage = $"@{moderator}, {message}";
        if (platform == "youtube")
            CPH.SendYouTubeMessage(finalMessage);
        else
            CPH.SendMessage(finalMessage);
    }

    private void SendMessageWithStyle(string baseKey, UserProfile profile, string platform, string user, params object[] args)
    {
        var messageArgs = new Dictionary<string, object>();
        messageArgs["0"] = user;
        for (int i = 0; i < args.Length; i++)
        {
            messageArgs[(i + 1).ToString()] = args[i];
        }

        string messageBody = GetBotMessage(profile, baseKey, messageArgs);
        // Pass to SendAdminMessage to handle the mention logic
        SendAdminMessage(messageBody, platform, user);
    }
}