// =================================================================================================
//  ADMIN: LIST BLOCKED USERS (!listblockedusers) - v12.1 - Fixed Formatting
//  Admin List Blocked Users
// =================================================================================================
//  - [FIX] Ensures all users in the list have an '@' prefix for consistency.
//  - [FIX] Standardized the bot response mention logic.
// =================================================================================================
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using TranslationBot; // Refers to the namespace defined in the shared library script

public class CPHInline
{
    private BotConfig config;
    private Dictionary<string, Dictionary<string, string>> messageTemplates;
    public bool Execute()
    {
        // 1. Determine Platform & Moderator Info
        string platform = args.ContainsKey("commandSource") && args["commandSource"].ToString().ToLower() == "youtube" ? "youtube" : "twitch";
        string moderator = args["user"].ToString();
        string moderatorId = args["userId"].ToString();
        // Dummy logger
        Action<string, string> logger = (s, m) =>
        {
        };
        // 2. Load Configuration
        config = BotHelpers.LoadJsonFile<BotConfig>(BotConstants.CONFIG_FILENAME, logger);
        messageTemplates = BotHelpers.LoadJsonFile<Dictionary<string, Dictionary<string, string>>>(BotConstants.TEMPLATES_FILENAME, logger);
        if (config == null || messageTemplates == null)
            return false;
        // 3. Proactive Logging / Profile Retrieval
        // Ensure we know the Admin's language preference for the response.
        UserProfile modProfile = BotHelpers.GetOrUpdateProfile(moderatorId, moderator, config, logger);
        // 4. Check if list is empty
        if (config.UserBlocklist.Count == 0)
        {
            SendMessageWithStyle("blockListUsersEmpty", modProfile, platform, moderator);
            return true;
        }

        // 5. Build the list string
        var listBuilder = new List<string>();
        foreach (var entry in config.UserBlocklist)
        {
            // entry.Key = UserID, entry.Value = Display Name
            string displayName = entry.Value;
            // FIX: Normalize the name to always have an '@'
            // This ensures consistent visual style: "@User1 (ID: 123), @User2 (ID: 456)"
            if (!displayName.StartsWith("@"))
            {
                displayName = "@" + displayName;
            }

            listBuilder.Add($"{displayName} (ID: {entry.Key})");
        }

        string formattedList = string.Join(", ", listBuilder);
        // 6. Send Result
        // "{0}, here are the blocked users: {1}"
        SendMessageWithStyle("blockListUsers", modProfile, platform, moderator, formattedList);
        return true;
    }

    // --- HELPER METHODS ---
    private string GetBotMessage(UserProfile profile, string baseKey, Dictionary<string, object> args = null)
    {
        if (args == null || args.Count == 0)
            return BotHelpers.GetBotMessage(profile, baseKey, messageTemplates, new object[0]);
        int maxIndex = -1;
        foreach (var key in args.Keys)
        {
            if (int.TryParse(key, out int index))
            {
                if (index > maxIndex)
                    maxIndex = index;
            }
        }

        if (maxIndex == -1)
            return BotHelpers.GetBotMessage(profile, baseKey, messageTemplates, new object[0]);
        object[] positionalArgs = new object[maxIndex + 1];
        for (int i = 0; i <= maxIndex; i++)
        {
            string key = i.ToString();
            positionalArgs[i] = args.ContainsKey(key) ? args[key] : "";
        }

        return BotHelpers.GetBotMessage(profile, baseKey, messageTemplates, positionalArgs);
    }

    // =========================================================================================
    // FIX APPLIED HERE: Consistent Messaging Wrapper
    // =========================================================================================
    private void SendAdminMessage(string message, string platform, string moderator)
    {
        // 1. If the message generated by the template already starts with the username 
        //    (e.g., "imtheanewbie, blocked users..."), we strip it out.
        //    This prevents duplication like "@imtheanewbie, imtheanewbie, blocked users..."
        if (message.StartsWith(moderator))
        {
            message = message.Substring(moderator.Length);
        }

        // 2. Clean up any leftover punctuation/spacing at the start
        message = message.TrimStart(',', ' ', ':');
        // 3. Force the @mention at the start
        string finalMessage = $"@{moderator}, {message}";
        if (platform == "youtube")
            CPH.SendYouTubeMessage(finalMessage);
        else
            CPH.SendMessage(finalMessage);
    }

    // Prepares arguments for the template engine
    private void SendMessageWithStyle(string baseKey, UserProfile profile, string platform, string user, params object[] args)
    {
        var messageArgs = new Dictionary<string, object>();
        messageArgs["0"] = user; // {0} corresponds to the moderator's name
        for (int i = 0; i < args.Length; i++)
        {
            messageArgs[(i + 1).ToString()] = args[i];
        }

        string messageBody = GetBotMessage(profile, baseKey, messageArgs);
        // Use the consistent Admin Message handler
        SendAdminMessage(messageBody, platform, user);
    }
}